### ISSUE TITLE
Plan MVP

### ISSUE THREAD

**Issue by Yukaii** [Yukaii/zuzugo-legacy#1]
from https://github.com/Yukaii/open-source-ideas/issues/6

### Features

- 根據地點進行篩選（跟上圖一樣用框框），串到任何能從地址拿到緯度的 API
- 根據到達特定地點的交通進行篩選（希望可以串到 Google Maps API）
- 根據價格篩選
- Slack bot/Email Notification（slack api/mailgun/twillio）
- 另外 Facebook 一堆沒地址的，需要提供回填機制

### Tasks

- [x] 591 API 研究 #2 
- [x] Facebook Group 社團商品 API 研究 #3
- [x] Agolia API 研究 - 其實第一階段就只要用 save object 和 search 而已，search 甚至還是自用 XD
- [x] 一般性架構規劃 (Technical stack、爬蟲架構等) #4
- [x] 591 爬蟲實作 #6 #5 
- [ ] Google Maps API 抓取
- [ ] Agolia 資料串接
- [ ] 資料篩選設定與實作
- [ ] 通知寄送 mailer 串接
- [ ] Landing Page 製作
- [ ] 水文吹一波

**Comment by Yukaii** [comment]
用 redis 或 rabbitMQ 之類的

- https://github.com/bee-queue/bee-queue
- https://github.com/squaremo/amqp.node

**Comment by Yukaii** [comment]
https://benbernardblog.com/the-tale-of-creating-a-distributed-web-crawler/

**Comment by Yukaii** [comment]
想了想最後可能都用 serverless 的方式實作了，circleCI 也有 cronjob 可以用。其實是最近在 g0v 看到某個 [civiltech 專案](https://github.com/CivicTechTO/civictechto-scripts) 的靈感 XD

成本特低 XDD
